"""Train and validate independent tabular baseline models.

The script consumes data/processed/prefix_train_features.csv generated by
build_prefix_dataset.py and trains one model per target:

- label_actionId
- label_pointId
- label_serverGetPoint

Validation is grouped by `match` by default because train/test have no match
overlap, making it the stricter split for this competition setup.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List

import joblib
import numpy as np
import pandas as pd
from pandas.api.types import is_numeric_dtype
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, f1_score, log_loss, roc_auc_score
from sklearn.model_selection import GroupKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder


TARGETS = {
    "actionId": {
        "label": "label_actionId",
        "classes": list(range(19)),
    },
    "pointId": {
        "label": "label_pointId",
        "classes": list(range(10)),
    },
    "serverGetPoint": {
        "label": "label_serverGetPoint",
        "classes": [0, 1],
    },
}

DROP_COLUMNS = {
    "sample_id",
    "rally_uid",
    "sample_weight",
    "label_actionId",
    "label_pointId",
    "label_serverGetPoint",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--train-features", default="data/processed/prefix_train_features.csv")
    parser.add_argument("--output-dir", default="models/tabular_baseline")
    parser.add_argument("--report-dir", default="reports/tabular_baseline")
    parser.add_argument("--group-col", default="match", choices=["match", "rally_uid"])
    parser.add_argument("--folds", type=int, default=5)
    parser.add_argument("--n-estimators", type=int, default=500)
    parser.add_argument("--max-depth", type=int, default=18)
    parser.add_argument("--min-samples-leaf", type=int, default=2)
    parser.add_argument("--random-state", type=int, default=42)
    parser.add_argument("--targets", nargs="+", default=list(TARGETS), choices=list(TARGETS))
    parser.add_argument("--sample", type=int, default=0, help="Optional debug row sample size; 0 means full data.")
    return parser.parse_args()


def make_feature_frame(df: pd.DataFrame, target_label: str) -> pd.DataFrame:
    drop = set(DROP_COLUMNS)
    # Metadata useful for grouping should not become a model feature.
    drop.update({"source_rally_len", "target_strikeNumber", target_label})
    feature_cols = [c for c in df.columns if c not in drop]
    return df[feature_cols].copy()


def split_columns(x: pd.DataFrame) -> tuple[List[str], List[str]]:
    numeric_cols = [c for c in x.columns if is_numeric_dtype(x[c])]
    categorical_cols = [c for c in x.columns if c not in numeric_cols]
    return numeric_cols, categorical_cols


def make_model(numeric_cols: List[str], categorical_cols: List[str], args: argparse.Namespace) -> Pipeline:
    numeric_pipe = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="median")),
        ]
    )
    categorical_pipe = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="most_frequent")),
            (
                "encoder",
                OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1),
            ),
        ]
    )
    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_pipe, numeric_cols),
            ("cat", categorical_pipe, categorical_cols),
        ],
        remainder="drop",
        verbose_feature_names_out=False,
    )
    clf = ExtraTreesClassifier(
        n_estimators=args.n_estimators,
        max_depth=args.max_depth,
        min_samples_leaf=args.min_samples_leaf,
        class_weight="balanced",
        n_jobs=-1,
        random_state=args.random_state,
    )
    return Pipeline(steps=[("preprocess", preprocessor), ("model", clf)])


def aligned_proba(model: Pipeline, x: pd.DataFrame, expected_classes: List[int]) -> np.ndarray:
    raw = model.predict_proba(x)
    model_classes = list(model.named_steps["model"].classes_)
    out = np.zeros((len(x), len(expected_classes)), dtype=float)
    for src_idx, cls in enumerate(model_classes):
        if cls in expected_classes:
            out[:, expected_classes.index(cls)] = raw[:, src_idx]
    row_sum = out.sum(axis=1, keepdims=True)
    out = np.divide(out, row_sum, out=np.full_like(out, 1.0 / len(expected_classes)), where=row_sum > 0)
    return out


def evaluate_target(df: pd.DataFrame, target_name: str, args: argparse.Namespace) -> Dict[str, object]:
    spec = TARGETS[target_name]
    label_col = spec["label"]
    classes = spec["classes"]

    x = make_feature_frame(df, label_col)
    y = df[label_col].astype(int).to_numpy()
    groups = df[args.group_col].to_numpy()
    weights = df["sample_weight"].astype(float).to_numpy() if "sample_weight" in df else None
    numeric_cols, categorical_cols = split_columns(x)

    unique_groups = len(pd.unique(groups))
    n_splits = min(args.folds, unique_groups)
    if n_splits < 2:
        raise ValueError(f"Need at least 2 groups for validation, got {unique_groups}")

    splitter = GroupKFold(n_splits=n_splits)
    rows = []
    oof_pred = np.zeros(len(df), dtype=int)
    oof_proba = np.zeros((len(df), len(classes)), dtype=float)

    for fold, (train_idx, valid_idx) in enumerate(splitter.split(x, y, groups), start=1):
        model = make_model(numeric_cols, categorical_cols, args)
        fit_kwargs = {}
        if weights is not None:
            fit_kwargs["model__sample_weight"] = weights[train_idx]
        model.fit(x.iloc[train_idx], y[train_idx], **fit_kwargs)

        proba = aligned_proba(model, x.iloc[valid_idx], classes)
        pred = np.asarray(classes)[np.argmax(proba, axis=1)]
        oof_pred[valid_idx] = pred
        oof_proba[valid_idx] = proba

        fold_metrics = {
            "target": target_name,
            "fold": fold,
            "valid_rows": int(len(valid_idx)),
            "valid_groups": int(len(pd.unique(groups[valid_idx]))),
            "accuracy": accuracy_score(y[valid_idx], pred),
            "macro_f1": f1_score(y[valid_idx], pred, average="macro", zero_division=0),
            "log_loss": log_loss(y[valid_idx], proba, labels=classes),
        }
        if target_name == "serverGetPoint" and len(np.unique(y[valid_idx])) > 1:
            fold_metrics["roc_auc"] = roc_auc_score(y[valid_idx], proba[:, classes.index(1)])
        rows.append(fold_metrics)
        print(
            f"{target_name} fold {fold}: "
            f"acc={fold_metrics['accuracy']:.5f} "
            f"macro_f1={fold_metrics['macro_f1']:.5f} "
            f"logloss={fold_metrics['log_loss']:.5f}"
        )

    summary = {
        "target": target_name,
        "group_col": args.group_col,
        "folds": n_splits,
        "rows": int(len(df)),
        "features": int(x.shape[1]),
        "numeric_features": len(numeric_cols),
        "categorical_features": len(categorical_cols),
        "oof_accuracy": accuracy_score(y, oof_pred),
        "oof_macro_f1": f1_score(y, oof_pred, average="macro", zero_division=0),
        "oof_log_loss": log_loss(y, oof_proba, labels=classes),
        "folds_detail": rows,
    }
    if target_name == "serverGetPoint" and len(np.unique(y)) > 1:
        summary["oof_roc_auc"] = roc_auc_score(y, oof_proba[:, classes.index(1)])

    # Fit final model on all data for later submission generation.
    final_model = make_model(numeric_cols, categorical_cols, args)
    fit_kwargs = {}
    if weights is not None:
        fit_kwargs["model__sample_weight"] = weights
    final_model.fit(x, y, **fit_kwargs)

    output_dir = Path(args.output_dir)
    report_dir = Path(args.report_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)

    joblib.dump(
        {
            "model": final_model,
            "feature_columns": list(x.columns),
            "classes": classes,
            "target": target_name,
            "label_col": label_col,
        },
        output_dir / f"{target_name}_extratrees.joblib",
    )
    pd.DataFrame(rows).to_csv(report_dir / f"{target_name}_fold_metrics.csv", index=False)
    np.save(report_dir / f"{target_name}_oof_proba.npy", oof_proba)
    pd.DataFrame({"sample_id": df["sample_id"], "y_true": y, "oof_pred": oof_pred}).to_csv(
        report_dir / f"{target_name}_oof_predictions.csv", index=False
    )
    return summary


def main() -> None:
    args = parse_args()
    np.random.seed(args.random_state)
    df = pd.read_csv(args.train_features)
    if args.sample and args.sample < len(df):
        df = df.sample(args.sample, random_state=args.random_state).reset_index(drop=True)

    all_summaries = []
    for target_name in args.targets:
        print(f"\n=== Training {target_name} baseline ===")
        summary = evaluate_target(df, target_name, args)
        all_summaries.append(summary)
        print(
            f"{target_name} OOF: "
            f"acc={summary['oof_accuracy']:.5f} "
            f"macro_f1={summary['oof_macro_f1']:.5f} "
            f"logloss={summary['oof_log_loss']:.5f}"
        )

    report_dir = Path(args.report_dir)
    report_dir.mkdir(parents=True, exist_ok=True)
    (report_dir / "summary.json").write_text(json.dumps(all_summaries, indent=2), encoding="utf-8")


if __name__ == "__main__":
    main()
